spring:
  config:
    activate:
      on-profile: "default"

build:
  version: "1.0"

accounts:
  message: "Default profile"
  contactDetails:
    name: "Max Potò"
    email: "maxpoto@gmail.com"
  onCallSupport: "32875343652"
  
